name: Terraform CI

on:
  pull_request:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  terraform-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Check Terraform formatting
        run: terraform fmt -check -recursive

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::509475591167:role/github-actions-terraform-role
          aws-region: us-east-2

      - name: Test AWS authentication
        run: aws sts get-caller-identity

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -input=falsename: Terraform CI


on: 
  pull_request:
    branches:
        - master


permissions:
  id-token: write
  contents: read


jobs:
  terraform-check:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3


      - name: Check Terraform formatting
        run: terraform fmt -check -recursive


      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform
        run: terraform validate


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::509475591167:role/github-actions-terraform-role
          aws-region: us-east-2


      - name: Test AWS authentication
        run: aws sts get-caller-identity
  

      - name: Terraform plan
        run: terraform plan -input=false
